import React, { useEffect, useState } from 'react';
import { Loader, Card, FormField } from '../components';

const RenderCard = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) =>
      <Card key={post._id} {...post} />
    );
  }

  return (
    <h2 className="text-[#6449ff] text-xl font-bold mt-5 uppercase">
      {title}
    </h2>
  );
}

const Home = () => {
  const [allPosts, setAllPosts] = useState(null);
  const [loading, setLoading] = useState(false);
  const [searchText, setSearchText] = useState('');

  return (
    <section className="max-w-7xl mx-auto">
      <h1 className="font-extrabold text-[#222328] text-[32px]">
        The Community Showcase
      </h1>
      <p className="text-[#646e75] text-[16px] mt-2 max-w-[500px]">
        Browse through a collection of imaginatve and visually stunning images generated by the DALL-E AI.
      </p>

      <div className="mt-8">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-xl mb-3 text-[#666e75]">
                Search results for{' '}
                <span className="text-[#222328]">
                  {searchText}
                </span>
              </h2>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 xs:grid-cols-2 gap-3">
              {searchText ? (
                <RenderCard
                  data={[]}
                  title="No results found"
                />
              ) : (
                <RenderCard
                  data={[]}
                  title="No posts found"
                />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home
